---
title: "Wesley Noble"
output: html_document
---
Email: wnoble@ucsb.edu Phone: 831-241-8303

---


### Summary
Rising senior at the University of California, Santa Barbara within the Education Opportunity Program. Double majoring in Environmental Studies (BS) and Physical Geography w/ an emphasis in Ocean Science (BS) with an expected graduation date of June 2021. Highly motivated and active student and employee with ample experience in spatial and data analysis, environmental planning, project monitoring, business sustainability and conservancy projects. 

---

### Education
- University of California, Santa Barbara (Enrolled 2017)
  - Double Majoring in Environmental Studies (BS) and Physical Geography w/ an emphasis in Ocean Science (BS)
  - GPA 3.44 
- Carmel High School (Graduated 2017) 
  - GPA 4.44, ACT 33
  
---

### Major Coursework
Linear Algebra, Physics, Ecology Evolution & Marine Biology, Chemistry, Molecular Cellular and Developmental Biology, Probability & Statistics, Toxicology, GIS, GIS for Environmental Applications, Remote Sensing, Writing for Environmental Professions, Economics Chemical Global Change, Biogeochemistry, Ocean Carbon Cycling, Oceanography, Ocean Circulation, Coastal Pollution, Meteorology, Stewardship Ethics, Sustainable Agriculture, Green Building 

---

## Skills
Experience working with R, Python, Java Script, ArcMap, ArcGIS Pro, QGIS, Word, Excel & PowerPoint

---

## Work Experience
- Santa Barbara Channel Keeper (October 2020 - Present)
  - MPA Watch Intern. Conduct weekly surveys of marine protected areas in the greater Goleta and Gaviota Coast area. Coordinate and contribute to volunteer information sessions. Perform simple data entry to our online platform for volunteer and personal surveys. Conduct quality assurance checks of other employees survey entries. 
- HAND Raster Modeling Design (August 2020 - Present)
  - PhD Student Research Assistant. Contributing in the development and experiment of Height Above Nearest Drainage (HAND) raster modeling. Reassessing the spatial resolution for the most accurate representation of 100-year flood events from the National Water Center’s stream flood gauge database.
- South Coast Deli Isla Vista (May 2019 - October 2020)
  - Assistant Manager. Monitor store inventory & utilities. Coordinate employee scheduling and training. Work register receiving in person & catering orders. Helped manage transition to COVID working environment.
- UCSB Greeks-Go-Green (October 2019 - Present)
  - Sustainability Analyst. Conducted flow gauge analysis of chapter houses. Implemented low-flow shower heads and faucet nozzles. Helped start recycling initiatives in multiple houses. Contributed to the outreach and coordination of the Eco-Friendly Market put on by GGG annually.
- Cal Coast Adventures (August 2018 - May 2019)
  - Surf Instructor & Kayak Tour Guide. Lead SUP and kayak tours around the Santa Barbara harbor. Gave personal surf lessons to individuals and groups. Responsible for renting out aquatic equipment at the West Beach station.
- Santa Lucia Preserve (June 2017 - August 2018)
  - Project Monitor. Located and satellite mapped over 900 At&T and PG&E electrical and power utility boxes throughout 20,000 acres of land. Monitored and helped the repiping of conduit and fiber-optic lining
  - Trail Maintenance. Maintained over 100 miles of open trails throughout the conservancy area of the preserve. Created 10+ miles of new trail in the backcountry of the conservancy area.
- Monterey Bay Aquarium Research Institute (MBARI) (June 2013-August 2014)
  - Research Science Intern. Assistant to marine research scientist, Jim Barry. Contributed in moving & monitoring sea creatures among salt water tanks

---

## Achievements and Awards
- LEED Green Associate
- Seymour Memorial Award - California Scholarship Federation (2017)
- High School Valedictorian (2017)

---

## Service Experiences
- Rancho Del Pueblo Farm
  - Weekly volunteer for Community Supported Agriculture organic farm in Ojai, Ca. Contribute in harvesting, washing, and distribution of subscription boxes for local residents.
- Amazing Day Foundation (2019)
  - Helped coordinate Walk for Life march at UCSB to commemorate the Amazing Day Foundation and its message to raise awareness for suicide prevention.
- Your Children’s Trees
  - Participated in the ongoing, environmental revival within Goleta by planting young trees and plants on public land.

---

## Activities
Isla Vista Surfrider Foundation member, UCSB Education Opportunity Program, UCSB Free Diving Club, Surfing, Spearfishing, Backpacking, Intramural Basketball

